{% set name = "captum" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/captum-{{ version }}.tar.gz
    sha256: 7ca87d0dc67b3b7589a730b970b9536172a5468e0e31bf8657fdd73abc568a33
  - git_url: https://github.com/pytorch/captum
    git_rev: v0.7.0
    folder: upstream

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - git  # [not win]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - matplotlib-base
    - numpy {{ numpy }}
    - pytorch >=1.6
    # seems to be optional since upstream says "It will try to use tqdm if available"
    # but it is also imported in production code
    - tqdm

test:
  source_files:
    - upstream/tests
  imports:
    - captum
    - captum._utils
  commands:
    - pip check
    - pytest upstream/tests
  requires:
    - pip
    - pytest
    - sphinx
    - mypy >=0.760
    - scikit-learn
    - parameterized
    - flask
    - flask-compress

about:
  home: https://captum.ai
  summary: Model interpretability for PyTorch
  dev_url: https://github.com/pytorch/captum
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Captum is a model interpretability and understanding library for PyTorch.
    Captum means comprehension in Latin and contains general purpose
    implementations of integrated gradients, saliency maps, smoothgrad,
    vargrad and others for PyTorch models. It has quick integration for models
    built with domain-specific libraries such as torchvision, torchtext, and others.

    *Captum is currently in beta and under active development!*

    PyPI: [https://pypi.org/project/captum/](https://pypi.org/project/captum/)

  doc_url: https://captum.ai/
  dev_url: https://github.com/pytorch/captum

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainers from package repo
    - NarineK
    - aobo-y
    - vivekmig
